# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

my_knn_cpp_pckg <- function(X, X0, y) {
    .Call(`_assignment1pckg_my_knn_cpp_pckg`, X, X0, y)
}

my_knn_mink_cpp <- function(X, X0, y, p) {
    .Call(`_assignment1pckg_my_knn_mink_cpp`, X, X0, y, p)
}

my_knn_mink_scaled_cpp <- function(X, X0, y, p, s) {
    .Call(`_assignment1pckg_my_knn_mink_scaled_cpp`, X, X0, y, p, s)
}

rcpp_hello_world <- function() {
    .Call(`_assignment1pckg_rcpp_hello_world`)
}

